import Foundation
import SwiftData

/// Represents a tag for categorizing journal entries
@Model
final class Tag {
    @Attribute(.unique) var id: UUID
    var name: String
    var color: String
    var createdAt: Date
    var isAutoGenerated: Bool

    @Relationship(inverse: \JournalEntry.tags) var entries: [JournalEntry]

    init(
        id: UUID = UUID(),
        name: String,
        color: String = "#007AFF",
        createdAt: Date = Date(),
        isAutoGenerated: Bool = false
    ) {
        self.id = id
        self.name = name
        self.color = color
        self.createdAt = createdAt
        self.isAutoGenerated = isAutoGenerated
        self.entries = []
    }
}
